import { combineReducers } from "redux";

const rootReducer = combineReducers({
  //   loginReducer,
  //   authCheckReducer,
  //   getDirectorsReducer,
  //   addDirectorReducer,
  //   deleteDirectorReducer,
  //   getChairmanSpeechReducer,
  //   addChairmanSpeechReducer,
  //   updateChairmanSpeechReducer,
  //   getClientsReducer,
  //   addClientReducer,
  //   deleteClientReducer,
  //   getAwardReducer,
  //   addAwardReducer,
  //   deleteAwardReducer,
  //   getNewsReducer,
  //   addNewsReducer,
  //   getContactReducer,
  //   getCareerReducer,
  //   addCareerReducer,
  //   updateCareerReducer,
  //   getApplicationsReducer,
  //   getProjectReducer,
  //   addProjectReducer,
  //   updateProjectReducer,
  //   deleteProjectReducer,
  //   getReportReducer,
  //   addReportReducer,
  //   deleteReportReducer,
  //   addAnnouncementReducer,
  //   getAnnouncementReducer,
  //   deleteAnnouncementReducer,
  //   getInvestorDetailReducer,
  //   addInvestorDetailReducer,
  //   getWallpaperReducer,
  //   addWallpaperReducer,
  //   deleteWallpaperReducer,
  //   getContentRequestReducer,
  //   addContentRequestReducer,
  //   rejectContentRequestReducer,
  //   processContentRequestReducer,
  //   addSiteOperationReducer,
  //   getSiteOperationReducer,
  //   getCompanyCredentialReducer,
  //   addCompanyCredentialReducer,
  //   getProjectHighlightReducer,
  //   addProjectHighlightReducer,
});

export default rootReducer;
